language: r
r:
  - release
  - devel
cache: packages

r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown

after_success:
  - Rscript -e 'covr::coveralls(function_exclusions="irmi*")'


notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
